global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'book-bazaar-app'
    static_configs:
      - targets: ['INSTANCE1_IP:3000']
    metrics_path: '/metrics'
