# Grafana Data Source Configuration
# This file can be imported into Grafana or used as reference

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      timeInterval: 15s
      queryTimeout: 60s
      httpHeaderName1: 'X-Custom-Header'
    secureJsonData:
      httpHeaderValue1: 'custom-value'
